
// Quotes
const localQuotes = [
    { text: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
    { text: "Your time is limited, don’t waste it living someone else’s life.", author: "Steve Jobs" },
    { text: "If you want something you’ve never had, you must be willing to do something you’ve never done.", author: "Thomas Jefferson" },
    { text: "Success is not how high you have climbed, but how you make a positive difference to the world.", author: "Roy T. Bennett" },
    { text: "It’s never too late to be what you might have been.", author: "George Eliot" },
    { text: "The best way to predict the future is to create it.", author: "Peter Drucker" },
    { text: "The biggest risk is not taking any risk.", author: "Mark Zuckerberg" },
    { text: "You don’t learn to walk by following rules. You learn by doing and falling over.", author: "Richard Branson" },
    { text: "Your most unhappy customers are your greatest source of learning.", author: "Bill Gates" },
    { text: "Do one thing every day that scares you.", author: "Eleanor Roosevelt" },
    { text: "The best way to get started is to quit talking and begin doing.", author: "Walt Disney" },
    { text: "The only way to achieve the impossible is to believe it is possible.", author: "Charles Kingsleigh" },
    { text: "Don’t be afraid to give up the good to go for the great.", author: "John D. Rockefeller" },
    { text: "If you are not willing to risk the usual, you will have to settle for the ordinary.", author: "Jim Rohn" },
    { text: "The greatest glory in living lies not in never falling, but in rising every time we fall.", author: "Nelson Mandela" },
    { text: "Believe you can and you’re halfway there.", author: "Theodore Roosevelt" },
    { text: "I find that the harder I work, the more luck I seem to have.", author: "Thomas Jefferson" },
    { text: "The only impossible journey is the one you never begin.", author: "Tony Robbins" },
    { text: "The purpose of our lives is to be happy.", author: "Dalai Lama" },
    { text: "Your passion is waiting for your courage to catch up.", author: "Isabelle Lafleche" },
    { text: "Everything you can imagine is real.", author: "Pablo Picasso" },
    { text: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
    { text: "What you get by achieving your goals is not as important as what you become by achieving your goals.", author: "Zig Ziglar" },
    { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
    { text: "I am not a product of my circumstances. I am a product of my decisions.", author: "Stephen Covey" },
    { text: "The best revenge is massive success.", author: "Frank Sinatra" },
    { text: "Your limitation—it’s only your imagination.", author: "Unknown" },
    { text: "Push yourself, because no one else is going to do it for you.", author: "Unknown" },
    { text: "Great things never come from comfort zones.", author: "Unknown" },
    { text: "Dream it. Wish it. Do it.", author: "Unknown" },
    { text: "Success doesn’t just find you. You have to go out and get it.", author: "Unknown" },
    { text: "The harder you work for something, the greater you’ll feel when you achieve it.", author: "Unknown" },
    { text: "Don’t stop when you’re tired. Stop when you’re done.", author: "Unknown" },
    { text: "Do something today that your future self will thank you for.", author: "Unknown" },
    { text: "Little things make big days.", author: "Unknown" },
    { text: "It’s going to be hard, but hard does not mean impossible.", author: "Unknown" },
    { text: "Don’t wait for opportunity. Create it.", author: "Unknown" },
    { text: "Sometimes we’re tested not to show our weaknesses, but to discover our strengths.", author: "Unknown" },
    { text: "The key to success is to focus on goals, not obstacles.", author: "Unknown" },
    { text: "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.", author: "Christian D. Larson" },
    { text: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson" },
    { text: "It’s not about how bad you want it. It’s about how hard you’re willing to work for it.", author: "Unknown" },
    { text: "Good things come to people who wait, but better things come to those who go out and get them.", author: "Unknown" },
    { text: "If you want to achieve greatness, stop asking for permission.", author: "Unknown" },
    { text: "Success is what happens after you have survived all of your mistakes.", author: "Unknown" },
    { text: "The only place where success comes before work is in the dictionary.", author: "Vidal Sassoon" },
    { text: "Keep your eyes on the stars, and your feet on the ground.", author: "Theodore Roosevelt" },
    { text: "You don’t need to be perfect to inspire others. Let people get inspired by how you deal with your imperfections.", author: "Unknown" }
];
